language: php

php:
  - 7.0
  - 7.1

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - bash .travis.sh
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpstan analyse -l4 src tests
  - vendor/bin/phan --project-root-directory --progress-bar -o phan.out

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
